/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        canvas: "#FAFAFA",
        surface: "#FFFFFF",
        sidebar: "#FFFFFF",
        "nav-hover": "#F5F5F5",
        "nav-active-bg": "#E6F4FF",
        "text-primary": "#0F172A",
        "text-secondary": "#64748B",
        "text-muted": "#94A3B8",
        border: "#EAECF0",
        divider: "#F0F0F0",
        accent: "#1677FF",
        "accent-hover": "#4096FF",
        success: "#52C41A",
        danger: "#FF4D4F",
        warning: "#FAAD14",
        info: "#1677FF",
        "badge-green-bg": "#F6FFED",
        "badge-green-text": "#52C41A",
        "badge-red-bg": "#FFF2F0",
        "badge-red-text": "#FF4D4F",
        "badge-amber-bg": "#FFFBE6",
        "badge-amber-text": "#FAAD14",
        "badge-blue-bg": "#E6F4FF",
        "badge-blue-text": "#1677FF",
      },
      fontFamily: {
        sans: [
          "-apple-system",
          "BlinkMacSystemFont",
          "'Segoe UI'",
          "Roboto",
          "'Helvetica Neue'",
          "Arial",
          "'Noto Sans'",
          "sans-serif",
        ],
      },
      borderRadius: {
        card: "8px",
        input: "6px",
        badge: "20px",
        btn: "6px",
      },
      fontSize: {
        "kpi": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "table-header": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
      spacing: {
        "18": "72px",
      },
    },
  },
  plugins: [],
};
